# .github/workflows/pr-cleanup.yml
name: Helm
on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Helm Deploy'
      uses: 'deliverybot/helm@v1.7.0'
      with:
        release: 'fluent-bit'
        namespace: 'default'
        chart: 'fluent/fluent-bit'
        repo: 'https://fluent.github.io/helm-charts'
        repo-alias: 'fluent'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
